# Julia wrapper for header: /usr/include/libxml2/libxml/globals.h
# Automatically generated using Clang.jl wrap_c, version 0.0.0

@c None xmlInitGlobals () shlib
@c None xmlCleanupGlobals () shlib
@c xmlParserInputBufferCreateFilenameFunc xmlParserInputBufferCreateFilenameDefault (:xmlParserInputBufferCreateFilenameFunc,) shlib
@c xmlOutputBufferCreateFilenameFunc xmlOutputBufferCreateFilenameDefault (:xmlOutputBufferCreateFilenameFunc,) shlib
@c None xmlInitializeGlobalState (:xmlGlobalStatePtr,) shlib
@c None xmlThrDefSetGenericErrorFunc (Ptr{:None},:xmlGenericErrorFunc) shlib
@c None xmlThrDefSetStructuredErrorFunc (Ptr{:None},:xmlStructuredErrorFunc) shlib
@c xmlRegisterNodeFunc xmlRegisterNodeDefault (:xmlRegisterNodeFunc,) shlib
@c xmlRegisterNodeFunc xmlThrDefRegisterNodeDefault (:xmlRegisterNodeFunc,) shlib
@c xmlDeregisterNodeFunc xmlDeregisterNodeDefault (:xmlDeregisterNodeFunc,) shlib
@c xmlDeregisterNodeFunc xmlThrDefDeregisterNodeDefault (:xmlDeregisterNodeFunc,) shlib
@c xmlOutputBufferCreateFilenameFunc xmlThrDefOutputBufferCreateFilenameDefault (:xmlOutputBufferCreateFilenameFunc,) shlib
@c xmlParserInputBufferCreateFilenameFunc xmlThrDefParserInputBufferCreateFilenameDefault (:xmlParserInputBufferCreateFilenameFunc,) shlib
@c Ptr{:xmlSAXHandlerV1} __docbDefaultSAXHandler () shlib
@c Ptr{:xmlSAXHandlerV1} __htmlDefaultSAXHandler () shlib
@c Ptr{:xmlError} __xmlLastError () shlib
@c Ptr{:Int32} __oldXMLWDcompatibility () shlib
@c Ptr{:xmlBufferAllocationScheme} __xmlBufferAllocScheme () shlib
@c xmlBufferAllocationScheme xmlThrDefBufferAllocScheme (:xmlBufferAllocationScheme,) shlib
@c Ptr{:Int32} __xmlDefaultBufferSize () shlib
@c Int32 xmlThrDefDefaultBufferSize (:Int32,) shlib
@c Ptr{:xmlSAXHandlerV1} __xmlDefaultSAXHandler () shlib
@c Ptr{:xmlSAXLocator} __xmlDefaultSAXLocator () shlib
@c Ptr{:Int32} __xmlDoValidityCheckingDefaultValue () shlib
@c Int32 xmlThrDefDoValidityCheckingDefaultValue (:Int32,) shlib
@c Ptr{:xmlGenericErrorFunc} __xmlGenericError () shlib
@c Ptr{:xmlStructuredErrorFunc} __xmlStructuredError () shlib
@c Ptr{Ptr{:None}} __xmlGenericErrorContext () shlib
@c Ptr{Ptr{:None}} __xmlStructuredErrorContext () shlib
@c Ptr{:Int32} __xmlGetWarningsDefaultValue () shlib
@c Int32 xmlThrDefGetWarningsDefaultValue (:Int32,) shlib
@c Ptr{:Int32} __xmlIndentTreeOutput () shlib
@c Int32 xmlThrDefIndentTreeOutput (:Int32,) shlib
@c Ptr{Ptr{:Uint8}} __xmlTreeIndentString () shlib
@c Ptr{:Uint8} xmlThrDefTreeIndentString (Ptr{:Uint8},) shlib
@c Ptr{:Int32} __xmlKeepBlanksDefaultValue () shlib
@c Int32 xmlThrDefKeepBlanksDefaultValue (:Int32,) shlib
@c Ptr{:Int32} __xmlLineNumbersDefaultValue () shlib
@c Int32 xmlThrDefLineNumbersDefaultValue (:Int32,) shlib
@c Ptr{:Int32} __xmlLoadExtDtdDefaultValue () shlib
@c Int32 xmlThrDefLoadExtDtdDefaultValue (:Int32,) shlib
@c Ptr{:Int32} __xmlParserDebugEntities () shlib
@c Int32 xmlThrDefParserDebugEntities (:Int32,) shlib
@c Ptr{Ptr{:Uint8}} __xmlParserVersion () shlib
@c Ptr{:Int32} __xmlPedanticParserDefaultValue () shlib
@c Int32 xmlThrDefPedanticParserDefaultValue (:Int32,) shlib
@c Ptr{:Int32} __xmlSaveNoEmptyTags () shlib
@c Int32 xmlThrDefSaveNoEmptyTags (:Int32,) shlib
@c Ptr{:Int32} __xmlSubstituteEntitiesDefaultValue () shlib
@c Int32 xmlThrDefSubstituteEntitiesDefaultValue (:Int32,) shlib
@c Ptr{:xmlRegisterNodeFunc} __xmlRegisterNodeDefaultValue () shlib
@c Ptr{:xmlDeregisterNodeFunc} __xmlDeregisterNodeDefaultValue () shlib
@c Ptr{:xmlParserInputBufferCreateFilenameFunc} __xmlParserInputBufferCreateFilenameValue () shlib
@c Ptr{:xmlOutputBufferCreateFilenameFunc} __xmlOutputBufferCreateFilenameValue () shlib

