# Julia wrapper for header: /usr/include/libxml2/libxml/parser.h
# Automatically generated using Clang.jl wrap_c, version 0.0.0

@c None xmlInitParser () shlib
@c None xmlCleanupParser () shlib
@c Int32 xmlParserInputRead (:xmlParserInputPtr,:Int32) shlib
@c Int32 xmlParserInputGrow (:xmlParserInputPtr,:Int32) shlib
@c xmlDocPtr xmlParseDoc (Ptr{:xmlChar},) shlib
@c xmlDocPtr xmlParseFile (Ptr{:Uint8},) shlib
@c xmlDocPtr xmlParseMemory (Ptr{:Uint8},:Int32) shlib
@c Int32 xmlSubstituteEntitiesDefault (:Int32,) shlib
@c Int32 xmlKeepBlanksDefault (:Int32,) shlib
@c None xmlStopParser (:xmlParserCtxtPtr,) shlib
@c Int32 xmlPedanticParserDefault (:Int32,) shlib
@c Int32 xmlLineNumbersDefault (:Int32,) shlib
@c xmlDocPtr xmlRecoverDoc (Ptr{:xmlChar},) shlib
@c xmlDocPtr xmlRecoverMemory (Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlRecoverFile (Ptr{:Uint8},) shlib
@c Int32 xmlParseDocument (:xmlParserCtxtPtr,) shlib
@c Int32 xmlParseExtParsedEnt (:xmlParserCtxtPtr,) shlib
@c Int32 xmlSAXUserParseFile (:xmlSAXHandlerPtr,Ptr{:None},Ptr{:Uint8}) shlib
@c Int32 xmlSAXUserParseMemory (:xmlSAXHandlerPtr,Ptr{:None},Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlSAXParseDoc (:xmlSAXHandlerPtr,Ptr{:xmlChar},:Int32) shlib
@c xmlDocPtr xmlSAXParseMemory (:xmlSAXHandlerPtr,Ptr{:Uint8},:Int32,:Int32) shlib
@c xmlDocPtr xmlSAXParseMemoryWithData (:xmlSAXHandlerPtr,Ptr{:Uint8},:Int32,:Int32,Ptr{:None}) shlib
@c xmlDocPtr xmlSAXParseFile (:xmlSAXHandlerPtr,Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlSAXParseFileWithData (:xmlSAXHandlerPtr,Ptr{:Uint8},:Int32,Ptr{:None}) shlib
@c xmlDocPtr xmlSAXParseEntity (:xmlSAXHandlerPtr,Ptr{:Uint8}) shlib
@c xmlDocPtr xmlParseEntity (Ptr{:Uint8},) shlib
@c xmlDtdPtr xmlSAXParseDTD (:xmlSAXHandlerPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlDtdPtr xmlParseDTD (Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlDtdPtr xmlIOParseDTD (:xmlSAXHandlerPtr,:xmlParserInputBufferPtr,:xmlCharEncoding) shlib
@c Int32 xmlParseBalancedChunkMemory (:xmlDocPtr,:xmlSAXHandlerPtr,Ptr{:None},:Int32,Ptr{:xmlChar},Ptr{:xmlNodePtr}) shlib
@c xmlParserErrors xmlParseInNodeContext (:xmlNodePtr,Ptr{:Uint8},:Int32,:Int32,Ptr{:xmlNodePtr}) shlib
@c Int32 xmlParseBalancedChunkMemoryRecover (:xmlDocPtr,:xmlSAXHandlerPtr,Ptr{:None},:Int32,Ptr{:xmlChar},Ptr{:xmlNodePtr},:Int32) shlib
@c Int32 xmlParseExternalEntity (:xmlDocPtr,:xmlSAXHandlerPtr,Ptr{:None},:Int32,Ptr{:xmlChar},Ptr{:xmlChar},Ptr{:xmlNodePtr}) shlib
@c Int32 xmlParseCtxtExternalEntity (:xmlParserCtxtPtr,Ptr{:xmlChar},Ptr{:xmlChar},Ptr{:xmlNodePtr}) shlib
@c xmlParserCtxtPtr xmlNewParserCtxt () shlib
@c Int32 xmlInitParserCtxt (:xmlParserCtxtPtr,) shlib
@c None xmlClearParserCtxt (:xmlParserCtxtPtr,) shlib
@c None xmlFreeParserCtxt (:xmlParserCtxtPtr,) shlib
@c None xmlSetupParserForBuffer (:xmlParserCtxtPtr,Ptr{:xmlChar},Ptr{:Uint8}) shlib
@c xmlParserCtxtPtr xmlCreateDocParserCtxt (Ptr{:xmlChar},) shlib
@c Int32 xmlGetFeaturesList (Ptr{:Int32},Ptr{Ptr{:Uint8}}) shlib
@c Int32 xmlGetFeature (:xmlParserCtxtPtr,Ptr{:Uint8},Ptr{:None}) shlib
@c Int32 xmlSetFeature (:xmlParserCtxtPtr,Ptr{:Uint8},Ptr{:None}) shlib
@c xmlParserCtxtPtr xmlCreatePushParserCtxt (:xmlSAXHandlerPtr,Ptr{:None},Ptr{:Uint8},:Int32,Ptr{:Uint8}) shlib
@c Int32 xmlParseChunk (:xmlParserCtxtPtr,Ptr{:Uint8},:Int32,:Int32) shlib
@c xmlParserCtxtPtr xmlCreateIOParserCtxt (:xmlSAXHandlerPtr,Ptr{:None},:xmlInputReadCallback,:xmlInputCloseCallback,Ptr{:None},:xmlCharEncoding) shlib
@c xmlParserInputPtr xmlNewIOInputStream (:xmlParserCtxtPtr,:xmlParserInputBufferPtr,:xmlCharEncoding) shlib
@c Ptr{:xmlParserNodeInfo} xmlParserFindNodeInfo (:xmlParserCtxtPtr,:xmlNodePtr) shlib
@c None xmlInitNodeInfoSeq (:xmlParserNodeInfoSeqPtr,) shlib
@c None xmlClearNodeInfoSeq (:xmlParserNodeInfoSeqPtr,) shlib
@c Uint64 xmlParserFindNodeInfoIndex (:xmlParserNodeInfoSeqPtr,:xmlNodePtr) shlib
@c None xmlParserAddNodeInfo (:xmlParserCtxtPtr,:xmlParserNodeInfoPtr) shlib
@c None xmlSetExternalEntityLoader (:xmlExternalEntityLoader,) shlib
@c xmlExternalEntityLoader xmlGetExternalEntityLoader () shlib
@c xmlParserInputPtr xmlLoadExternalEntity (Ptr{:Uint8},Ptr{:Uint8},:xmlParserCtxtPtr) shlib
@c Int64 xmlByteConsumed (:xmlParserCtxtPtr,) shlib
@c None xmlCtxtReset (:xmlParserCtxtPtr,) shlib
@c Int32 xmlCtxtResetPush (:xmlParserCtxtPtr,Ptr{:Uint8},:Int32,Ptr{:Uint8},Ptr{:Uint8}) shlib
@c Int32 xmlCtxtUseOptions (:xmlParserCtxtPtr,:Int32) shlib
@c xmlDocPtr xmlReadDoc (Ptr{:xmlChar},Ptr{:Uint8},Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlReadFile (Ptr{:Uint8},Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlReadMemory (Ptr{:Uint8},:Int32,Ptr{:Uint8},Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlReadFd (:Int32,Ptr{:Uint8},Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlReadIO (:xmlInputReadCallback,:xmlInputCloseCallback,Ptr{:None},Ptr{:Uint8},Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlCtxtReadDoc (:xmlParserCtxtPtr,Ptr{:xmlChar},Ptr{:Uint8},Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlCtxtReadFile (:xmlParserCtxtPtr,Ptr{:Uint8},Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlCtxtReadMemory (:xmlParserCtxtPtr,Ptr{:Uint8},:Int32,Ptr{:Uint8},Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlCtxtReadFd (:xmlParserCtxtPtr,:Int32,Ptr{:Uint8},Ptr{:Uint8},:Int32) shlib
@c xmlDocPtr xmlCtxtReadIO (:xmlParserCtxtPtr,:xmlInputReadCallback,:xmlInputCloseCallback,Ptr{:None},Ptr{:Uint8},Ptr{:Uint8},:Int32) shlib
@c Int32 xmlHasFeature (:xmlFeature,) shlib

