# Julia wrapper for header: /usr/include/libxml2/libxml/tree.h
# Automatically generated using Clang.jl wrap_c, version 0.0.0

@c Int32 xmlValidateNCName (Ptr{:xmlChar},:Int32) shlib
@c Int32 xmlValidateQName (Ptr{:xmlChar},:Int32) shlib
@c Int32 xmlValidateName (Ptr{:xmlChar},:Int32) shlib
@c Int32 xmlValidateNMToken (Ptr{:xmlChar},:Int32) shlib
@c Ptr{:xmlChar} xmlBuildQName (Ptr{:xmlChar},Ptr{:xmlChar},Ptr{:xmlChar},:Int32) shlib
@c Ptr{:xmlChar} xmlSplitQName2 (Ptr{:xmlChar},Ptr{Ptr{:xmlChar}}) shlib
@c Ptr{:xmlChar} xmlSplitQName3 (Ptr{:xmlChar},Ptr{:Int32}) shlib
@c None xmlSetBufferAllocationScheme (:xmlBufferAllocationScheme,) shlib
@c xmlBufferAllocationScheme xmlGetBufferAllocationScheme () shlib
@c xmlBufferPtr xmlBufferCreate () shlib
@c xmlBufferPtr xmlBufferCreateSize (:size_t,) shlib
@c xmlBufferPtr xmlBufferCreateStatic (Ptr{:None},:size_t) shlib
@c Int32 xmlBufferResize (:xmlBufferPtr,:Uint32) shlib
@c None xmlBufferFree (:xmlBufferPtr,) shlib
@c Int32 xmlBufferDump (Ptr{:FILE},:xmlBufferPtr) shlib
@c Int32 xmlBufferAdd (:xmlBufferPtr,Ptr{:xmlChar},:Int32) shlib
@c Int32 xmlBufferAddHead (:xmlBufferPtr,Ptr{:xmlChar},:Int32) shlib
@c Int32 xmlBufferCat (:xmlBufferPtr,Ptr{:xmlChar}) shlib
@c Int32 xmlBufferCCat (:xmlBufferPtr,Ptr{:Uint8}) shlib
@c Int32 xmlBufferShrink (:xmlBufferPtr,:Uint32) shlib
@c Int32 xmlBufferGrow (:xmlBufferPtr,:Uint32) shlib
@c None xmlBufferEmpty (:xmlBufferPtr,) shlib
@c Ptr{:xmlChar} xmlBufferContent (:xmlBufferPtr,) shlib
@c None xmlBufferSetAllocationScheme (:xmlBufferPtr,:xmlBufferAllocationScheme) shlib
@c Int32 xmlBufferLength (:xmlBufferPtr,) shlib
@c xmlDtdPtr xmlCreateIntSubset (:xmlDocPtr,Ptr{:xmlChar},Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlDtdPtr xmlNewDtd (:xmlDocPtr,Ptr{:xmlChar},Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlDtdPtr xmlGetIntSubset (:xmlDocPtr,) shlib
@c None xmlFreeDtd (:xmlDtdPtr,) shlib
@c xmlNsPtr xmlNewGlobalNs (:xmlDocPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlNsPtr xmlNewNs (:xmlNodePtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c None xmlFreeNs (:xmlNsPtr,) shlib
@c None xmlFreeNsList (:xmlNsPtr,) shlib
@c xmlDocPtr xmlNewDoc (Ptr{:xmlChar},) shlib
@c None xmlFreeDoc (:xmlDocPtr,) shlib
@c xmlAttrPtr xmlNewDocProp (:xmlDocPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlAttrPtr xmlNewProp (:xmlNodePtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlAttrPtr xmlNewNsProp (:xmlNodePtr,:xmlNsPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlAttrPtr xmlNewNsPropEatName (:xmlNodePtr,:xmlNsPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c None xmlFreePropList (:xmlAttrPtr,) shlib
@c None xmlFreeProp (:xmlAttrPtr,) shlib
@c xmlAttrPtr xmlCopyProp (:xmlNodePtr,:xmlAttrPtr) shlib
@c xmlAttrPtr xmlCopyPropList (:xmlNodePtr,:xmlAttrPtr) shlib
@c xmlDtdPtr xmlCopyDtd (:xmlDtdPtr,) shlib
@c xmlDocPtr xmlCopyDoc (:xmlDocPtr,:Int32) shlib
@c xmlNodePtr xmlNewDocNode (:xmlDocPtr,:xmlNsPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewDocNodeEatName (:xmlDocPtr,:xmlNsPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewNode (:xmlNsPtr,Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewNodeEatName (:xmlNsPtr,Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewChild (:xmlNodePtr,:xmlNsPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewDocText (:xmlDocPtr,Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewText (Ptr{:xmlChar},) shlib
@c xmlNodePtr xmlNewDocPI (:xmlDocPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewPI (Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewDocTextLen (:xmlDocPtr,Ptr{:xmlChar},:Int32) shlib
@c xmlNodePtr xmlNewTextLen (Ptr{:xmlChar},:Int32) shlib
@c xmlNodePtr xmlNewDocComment (:xmlDocPtr,Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewComment (Ptr{:xmlChar},) shlib
@c xmlNodePtr xmlNewCDataBlock (:xmlDocPtr,Ptr{:xmlChar},:Int32) shlib
@c xmlNodePtr xmlNewCharRef (:xmlDocPtr,Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewReference (:xmlDocPtr,Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlCopyNode (:xmlNodePtr,:Int32) shlib
@c xmlNodePtr xmlDocCopyNode (:xmlNodePtr,:xmlDocPtr,:Int32) shlib
@c xmlNodePtr xmlDocCopyNodeList (:xmlDocPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlCopyNodeList (:xmlNodePtr,) shlib
@c xmlNodePtr xmlNewTextChild (:xmlNodePtr,:xmlNsPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewDocRawNode (:xmlDocPtr,:xmlNsPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlNewDocFragment (:xmlDocPtr,) shlib
@c Int64 xmlGetLineNo (:xmlNodePtr,) shlib
@c Ptr{:xmlChar} xmlGetNodePath (:xmlNodePtr,) shlib
@c xmlNodePtr xmlDocGetRootElement (:xmlDocPtr,) shlib
@c xmlNodePtr xmlGetLastChild (:xmlNodePtr,) shlib
@c Int32 xmlNodeIsText (:xmlNodePtr,) shlib
@c Int32 xmlIsBlankNode (:xmlNodePtr,) shlib
@c xmlNodePtr xmlDocSetRootElement (:xmlDocPtr,:xmlNodePtr) shlib
@c None xmlNodeSetName (:xmlNodePtr,Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlAddChild (:xmlNodePtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlAddChildList (:xmlNodePtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlReplaceNode (:xmlNodePtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlAddPrevSibling (:xmlNodePtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlAddSibling (:xmlNodePtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlAddNextSibling (:xmlNodePtr,:xmlNodePtr) shlib
@c None xmlUnlinkNode (:xmlNodePtr,) shlib
@c xmlNodePtr xmlTextMerge (:xmlNodePtr,:xmlNodePtr) shlib
@c Int32 xmlTextConcat (:xmlNodePtr,Ptr{:xmlChar},:Int32) shlib
@c None xmlFreeNodeList (:xmlNodePtr,) shlib
@c None xmlFreeNode (:xmlNodePtr,) shlib
@c None xmlSetTreeDoc (:xmlNodePtr,:xmlDocPtr) shlib
@c None xmlSetListDoc (:xmlNodePtr,:xmlDocPtr) shlib
@c xmlNsPtr xmlSearchNs (:xmlDocPtr,:xmlNodePtr,Ptr{:xmlChar}) shlib
@c xmlNsPtr xmlSearchNsByHref (:xmlDocPtr,:xmlNodePtr,Ptr{:xmlChar}) shlib
@c Ptr{:xmlNsPtr} xmlGetNsList (:xmlDocPtr,:xmlNodePtr) shlib
@c None xmlSetNs (:xmlNodePtr,:xmlNsPtr) shlib
@c xmlNsPtr xmlCopyNamespace (:xmlNsPtr,) shlib
@c xmlNsPtr xmlCopyNamespaceList (:xmlNsPtr,) shlib
@c xmlAttrPtr xmlSetProp (:xmlNodePtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlAttrPtr xmlSetNsProp (:xmlNodePtr,:xmlNsPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c Ptr{:xmlChar} xmlGetNoNsProp (:xmlNodePtr,Ptr{:xmlChar}) shlib
@c Ptr{:xmlChar} xmlGetProp (:xmlNodePtr,Ptr{:xmlChar}) shlib
@c xmlAttrPtr xmlHasProp (:xmlNodePtr,Ptr{:xmlChar}) shlib
@c xmlAttrPtr xmlHasNsProp (:xmlNodePtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c Ptr{:xmlChar} xmlGetNsProp (:xmlNodePtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlStringGetNodeList (:xmlDocPtr,Ptr{:xmlChar}) shlib
@c xmlNodePtr xmlStringLenGetNodeList (:xmlDocPtr,Ptr{:xmlChar},:Int32) shlib
@c Ptr{:xmlChar} xmlNodeListGetString (:xmlDocPtr,:xmlNodePtr,:Int32) shlib
@c Ptr{:xmlChar} xmlNodeListGetRawString (:xmlDocPtr,:xmlNodePtr,:Int32) shlib
@c None xmlNodeSetContent (:xmlNodePtr,Ptr{:xmlChar}) shlib
@c None xmlNodeSetContentLen (:xmlNodePtr,Ptr{:xmlChar},:Int32) shlib
@c None xmlNodeAddContent (:xmlNodePtr,Ptr{:xmlChar}) shlib
@c None xmlNodeAddContentLen (:xmlNodePtr,Ptr{:xmlChar},:Int32) shlib
@c Ptr{:xmlChar} xmlNodeGetContent (:xmlNodePtr,) shlib
@c Int32 xmlNodeBufGetContent (:xmlBufferPtr,:xmlNodePtr) shlib
@c Ptr{:xmlChar} xmlNodeGetLang (:xmlNodePtr,) shlib
@c Int32 xmlNodeGetSpacePreserve (:xmlNodePtr,) shlib
@c None xmlNodeSetLang (:xmlNodePtr,Ptr{:xmlChar}) shlib
@c None xmlNodeSetSpacePreserve (:xmlNodePtr,:Int32) shlib
@c Ptr{:xmlChar} xmlNodeGetBase (:xmlDocPtr,:xmlNodePtr) shlib
@c None xmlNodeSetBase (:xmlNodePtr,Ptr{:xmlChar}) shlib
@c Int32 xmlRemoveProp (:xmlAttrPtr,) shlib
@c Int32 xmlUnsetNsProp (:xmlNodePtr,:xmlNsPtr,Ptr{:xmlChar}) shlib
@c Int32 xmlUnsetProp (:xmlNodePtr,Ptr{:xmlChar}) shlib
@c None xmlBufferWriteCHAR (:xmlBufferPtr,Ptr{:xmlChar}) shlib
@c None xmlBufferWriteChar (:xmlBufferPtr,Ptr{:Uint8}) shlib
@c None xmlBufferWriteQuotedString (:xmlBufferPtr,Ptr{:xmlChar}) shlib
@c None xmlAttrSerializeTxtContent (:xmlBufferPtr,:xmlDocPtr,:xmlAttrPtr,Ptr{:xmlChar}) shlib
@c Int32 xmlReconciliateNs (:xmlDocPtr,:xmlNodePtr) shlib
@c None xmlDocDumpFormatMemory (:xmlDocPtr,Ptr{Ptr{:xmlChar}},Ptr{:Int32},:Int32) shlib
@c None xmlDocDumpMemory (:xmlDocPtr,Ptr{Ptr{:xmlChar}},Ptr{:Int32}) shlib
@c None xmlDocDumpMemoryEnc (:xmlDocPtr,Ptr{Ptr{:xmlChar}},Ptr{:Int32},Ptr{:Uint8}) shlib
@c None xmlDocDumpFormatMemoryEnc (:xmlDocPtr,Ptr{Ptr{:xmlChar}},Ptr{:Int32},Ptr{:Uint8},:Int32) shlib
@c Int32 xmlDocFormatDump (Ptr{:FILE},:xmlDocPtr,:Int32) shlib
@c Int32 xmlDocDump (Ptr{:FILE},:xmlDocPtr) shlib
@c None xmlElemDump (Ptr{:FILE},:xmlDocPtr,:xmlNodePtr) shlib
@c Int32 xmlSaveFile (Ptr{:Uint8},:xmlDocPtr) shlib
@c Int32 xmlSaveFormatFile (Ptr{:Uint8},:xmlDocPtr,:Int32) shlib
@c Int32 xmlNodeDump (:xmlBufferPtr,:xmlDocPtr,:xmlNodePtr,:Int32,:Int32) shlib
@c Int32 xmlSaveFileTo (:xmlOutputBufferPtr,:xmlDocPtr,Ptr{:Uint8}) shlib
@c Int32 xmlSaveFormatFileTo (:xmlOutputBufferPtr,:xmlDocPtr,Ptr{:Uint8},:Int32) shlib
@c None xmlNodeDumpOutput (:xmlOutputBufferPtr,:xmlDocPtr,:xmlNodePtr,:Int32,:Int32,Ptr{:Uint8}) shlib
@c Int32 xmlSaveFormatFileEnc (Ptr{:Uint8},:xmlDocPtr,Ptr{:Uint8},:Int32) shlib
@c Int32 xmlSaveFileEnc (Ptr{:Uint8},:xmlDocPtr,Ptr{:Uint8}) shlib
@c Int32 xmlIsXHTML (Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c Int32 xmlGetDocCompressMode (:xmlDocPtr,) shlib
@c None xmlSetDocCompressMode (:xmlDocPtr,:Int32) shlib
@c Int32 xmlGetCompressMode () shlib
@c None xmlSetCompressMode (:Int32,) shlib
@c xmlDOMWrapCtxtPtr xmlDOMWrapNewCtxt () shlib
@c None xmlDOMWrapFreeCtxt (:xmlDOMWrapCtxtPtr,) shlib
@c Int32 xmlDOMWrapReconcileNamespaces (:xmlDOMWrapCtxtPtr,:xmlNodePtr,:Int32) shlib
@c Int32 xmlDOMWrapAdoptNode (:xmlDOMWrapCtxtPtr,:xmlDocPtr,:xmlNodePtr,:xmlDocPtr,:xmlNodePtr,:Int32) shlib
@c Int32 xmlDOMWrapRemoveNode (:xmlDOMWrapCtxtPtr,:xmlDocPtr,:xmlNodePtr,:Int32) shlib
@c Int32 xmlDOMWrapCloneNode (:xmlDOMWrapCtxtPtr,:xmlDocPtr,:xmlNodePtr,Ptr{:xmlNodePtr},:xmlDocPtr,:xmlNodePtr,:Int32,:Int32) shlib
@c Uint64 xmlChildElementCount (:xmlNodePtr,) shlib
@c xmlNodePtr xmlNextElementSibling (:xmlNodePtr,) shlib
@c xmlNodePtr xmlFirstElementChild (:xmlNodePtr,) shlib
@c xmlNodePtr xmlLastElementChild (:xmlNodePtr,) shlib
@c xmlNodePtr xmlPreviousElementSibling (:xmlNodePtr,) shlib

