# Julia wrapper for header: /usr/include/libxml2/libxml/valid.h
# Automatically generated using Clang.jl wrap_c, version 0.0.0

@c xmlNotationPtr xmlAddNotationDecl (:xmlValidCtxtPtr,:xmlDtdPtr,Ptr{:xmlChar},Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlNotationTablePtr xmlCopyNotationTable (:xmlNotationTablePtr,) shlib
@c None xmlFreeNotationTable (:xmlNotationTablePtr,) shlib
@c None xmlDumpNotationDecl (:xmlBufferPtr,:xmlNotationPtr) shlib
@c None xmlDumpNotationTable (:xmlBufferPtr,:xmlNotationTablePtr) shlib
@c xmlElementContentPtr xmlNewElementContent (Ptr{:xmlChar},:xmlElementContentType) shlib
@c xmlElementContentPtr xmlCopyElementContent (:xmlElementContentPtr,) shlib
@c None xmlFreeElementContent (:xmlElementContentPtr,) shlib
@c xmlElementContentPtr xmlNewDocElementContent (:xmlDocPtr,Ptr{:xmlChar},:xmlElementContentType) shlib
@c xmlElementContentPtr xmlCopyDocElementContent (:xmlDocPtr,:xmlElementContentPtr) shlib
@c None xmlFreeDocElementContent (:xmlDocPtr,:xmlElementContentPtr) shlib
@c None xmlSnprintfElementContent (Ptr{:Uint8},:Int32,:xmlElementContentPtr,:Int32) shlib
@c None xmlSprintfElementContent (Ptr{:Uint8},:xmlElementContentPtr,:Int32) shlib
@c xmlElementPtr xmlAddElementDecl (:xmlValidCtxtPtr,:xmlDtdPtr,Ptr{:xmlChar},:xmlElementTypeVal,:xmlElementContentPtr) shlib
@c xmlElementTablePtr xmlCopyElementTable (:xmlElementTablePtr,) shlib
@c None xmlFreeElementTable (:xmlElementTablePtr,) shlib
@c None xmlDumpElementTable (:xmlBufferPtr,:xmlElementTablePtr) shlib
@c None xmlDumpElementDecl (:xmlBufferPtr,:xmlElementPtr) shlib
@c xmlEnumerationPtr xmlCreateEnumeration (Ptr{:xmlChar},) shlib
@c None xmlFreeEnumeration (:xmlEnumerationPtr,) shlib
@c xmlEnumerationPtr xmlCopyEnumeration (:xmlEnumerationPtr,) shlib
@c xmlAttributePtr xmlAddAttributeDecl (:xmlValidCtxtPtr,:xmlDtdPtr,Ptr{:xmlChar},Ptr{:xmlChar},Ptr{:xmlChar},:xmlAttributeType,:xmlAttributeDefault,Ptr{:xmlChar},:xmlEnumerationPtr) shlib
@c xmlAttributeTablePtr xmlCopyAttributeTable (:xmlAttributeTablePtr,) shlib
@c None xmlFreeAttributeTable (:xmlAttributeTablePtr,) shlib
@c None xmlDumpAttributeTable (:xmlBufferPtr,:xmlAttributeTablePtr) shlib
@c None xmlDumpAttributeDecl (:xmlBufferPtr,:xmlAttributePtr) shlib
@c xmlIDPtr xmlAddID (:xmlValidCtxtPtr,:xmlDocPtr,Ptr{:xmlChar},:xmlAttrPtr) shlib
@c None xmlFreeIDTable (:xmlIDTablePtr,) shlib
@c xmlAttrPtr xmlGetID (:xmlDocPtr,Ptr{:xmlChar}) shlib
@c Int32 xmlIsID (:xmlDocPtr,:xmlNodePtr,:xmlAttrPtr) shlib
@c Int32 xmlRemoveID (:xmlDocPtr,:xmlAttrPtr) shlib
@c xmlRefPtr xmlAddRef (:xmlValidCtxtPtr,:xmlDocPtr,Ptr{:xmlChar},:xmlAttrPtr) shlib
@c None xmlFreeRefTable (:xmlRefTablePtr,) shlib
@c Int32 xmlIsRef (:xmlDocPtr,:xmlNodePtr,:xmlAttrPtr) shlib
@c Int32 xmlRemoveRef (:xmlDocPtr,:xmlAttrPtr) shlib
@c xmlListPtr xmlGetRefs (:xmlDocPtr,Ptr{:xmlChar}) shlib
@c xmlValidCtxtPtr xmlNewValidCtxt () shlib
@c None xmlFreeValidCtxt (:xmlValidCtxtPtr,) shlib
@c Int32 xmlValidateRoot (:xmlValidCtxtPtr,:xmlDocPtr) shlib
@c Int32 xmlValidateElementDecl (:xmlValidCtxtPtr,:xmlDocPtr,:xmlElementPtr) shlib
@c Ptr{:xmlChar} xmlValidNormalizeAttributeValue (:xmlDocPtr,:xmlNodePtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c Ptr{:xmlChar} xmlValidCtxtNormalizeAttributeValue (:xmlValidCtxtPtr,:xmlDocPtr,:xmlNodePtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c Int32 xmlValidateAttributeDecl (:xmlValidCtxtPtr,:xmlDocPtr,:xmlAttributePtr) shlib
@c Int32 xmlValidateAttributeValue (:xmlAttributeType,Ptr{:xmlChar}) shlib
@c Int32 xmlValidateNotationDecl (:xmlValidCtxtPtr,:xmlDocPtr,:xmlNotationPtr) shlib
@c Int32 xmlValidateDtd (:xmlValidCtxtPtr,:xmlDocPtr,:xmlDtdPtr) shlib
@c Int32 xmlValidateDtdFinal (:xmlValidCtxtPtr,:xmlDocPtr) shlib
@c Int32 xmlValidateDocument (:xmlValidCtxtPtr,:xmlDocPtr) shlib
@c Int32 xmlValidateElement (:xmlValidCtxtPtr,:xmlDocPtr,:xmlNodePtr) shlib
@c Int32 xmlValidateOneElement (:xmlValidCtxtPtr,:xmlDocPtr,:xmlNodePtr) shlib
@c Int32 xmlValidateOneAttribute (:xmlValidCtxtPtr,:xmlDocPtr,:xmlNodePtr,:xmlAttrPtr,Ptr{:xmlChar}) shlib
@c Int32 xmlValidateOneNamespace (:xmlValidCtxtPtr,:xmlDocPtr,:xmlNodePtr,Ptr{:xmlChar},:xmlNsPtr,Ptr{:xmlChar}) shlib
@c Int32 xmlValidateDocumentFinal (:xmlValidCtxtPtr,:xmlDocPtr) shlib
@c Int32 xmlValidateNotationUse (:xmlValidCtxtPtr,:xmlDocPtr,Ptr{:xmlChar}) shlib
@c Int32 xmlIsMixedElement (:xmlDocPtr,Ptr{:xmlChar}) shlib
@c xmlAttributePtr xmlGetDtdAttrDesc (:xmlDtdPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlAttributePtr xmlGetDtdQAttrDesc (:xmlDtdPtr,Ptr{:xmlChar},Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlNotationPtr xmlGetDtdNotationDesc (:xmlDtdPtr,Ptr{:xmlChar}) shlib
@c xmlElementPtr xmlGetDtdQElementDesc (:xmlDtdPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c xmlElementPtr xmlGetDtdElementDesc (:xmlDtdPtr,Ptr{:xmlChar}) shlib
@c Int32 xmlValidGetPotentialChildren (Ptr{:xmlElementContent},Ptr{Ptr{:xmlChar}},Ptr{:Int32},:Int32) shlib
@c Int32 xmlValidGetValidElements (Ptr{:xmlNode},Ptr{:xmlNode},Ptr{Ptr{:xmlChar}},:Int32) shlib
@c Int32 xmlValidateNameValue (Ptr{:xmlChar},) shlib
@c Int32 xmlValidateNamesValue (Ptr{:xmlChar},) shlib
@c Int32 xmlValidateNmtokenValue (Ptr{:xmlChar},) shlib
@c Int32 xmlValidateNmtokensValue (Ptr{:xmlChar},) shlib
@c Int32 xmlValidBuildContentModel (:xmlValidCtxtPtr,:xmlElementPtr) shlib
@c Int32 xmlValidatePushElement (:xmlValidCtxtPtr,:xmlDocPtr,:xmlNodePtr,Ptr{:xmlChar}) shlib
@c Int32 xmlValidatePushCData (:xmlValidCtxtPtr,Ptr{:xmlChar},:Int32) shlib
@c Int32 xmlValidatePopElement (:xmlValidCtxtPtr,:xmlDocPtr,:xmlNodePtr,Ptr{:xmlChar}) shlib

