# Julia wrapper for header: /usr/include/libxml2/libxml/xpathInternals.h
# Automatically generated using Clang.jl wrap_c, version 0.0.0

@c Int32 xmlXPathPopBoolean (:xmlXPathParserContextPtr,) shlib
@c Float64 xmlXPathPopNumber (:xmlXPathParserContextPtr,) shlib
@c Ptr{:xmlChar} xmlXPathPopString (:xmlXPathParserContextPtr,) shlib
@c xmlNodeSetPtr xmlXPathPopNodeSet (:xmlXPathParserContextPtr,) shlib
@c Ptr{:None} xmlXPathPopExternal (:xmlXPathParserContextPtr,) shlib
@c None xmlXPathRegisterVariableLookup (:xmlXPathContextPtr,:xmlXPathVariableLookupFunc,Ptr{:None}) shlib
@c None xmlXPathRegisterFuncLookup (:xmlXPathContextPtr,:xmlXPathFuncLookupFunc,Ptr{:None}) shlib
@c None xmlXPatherror (:xmlXPathParserContextPtr,Ptr{:Uint8},:Int32,:Int32) shlib
@c None xmlXPathErr (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathDebugDumpObject (Ptr{:FILE},:xmlXPathObjectPtr,:Int32) shlib
@c None xmlXPathDebugDumpCompExpr (Ptr{:FILE},:xmlXPathCompExprPtr,:Int32) shlib
@c Int32 xmlXPathNodeSetContains (:xmlNodeSetPtr,:xmlNodePtr) shlib
@c xmlNodeSetPtr xmlXPathDifference (:xmlNodeSetPtr,:xmlNodeSetPtr) shlib
@c xmlNodeSetPtr xmlXPathIntersection (:xmlNodeSetPtr,:xmlNodeSetPtr) shlib
@c xmlNodeSetPtr xmlXPathDistinctSorted (:xmlNodeSetPtr,) shlib
@c xmlNodeSetPtr xmlXPathDistinct (:xmlNodeSetPtr,) shlib
@c Int32 xmlXPathHasSameNodes (:xmlNodeSetPtr,:xmlNodeSetPtr) shlib
@c xmlNodeSetPtr xmlXPathNodeLeadingSorted (:xmlNodeSetPtr,:xmlNodePtr) shlib
@c xmlNodeSetPtr xmlXPathLeadingSorted (:xmlNodeSetPtr,:xmlNodeSetPtr) shlib
@c xmlNodeSetPtr xmlXPathNodeLeading (:xmlNodeSetPtr,:xmlNodePtr) shlib
@c xmlNodeSetPtr xmlXPathLeading (:xmlNodeSetPtr,:xmlNodeSetPtr) shlib
@c xmlNodeSetPtr xmlXPathNodeTrailingSorted (:xmlNodeSetPtr,:xmlNodePtr) shlib
@c xmlNodeSetPtr xmlXPathTrailingSorted (:xmlNodeSetPtr,:xmlNodeSetPtr) shlib
@c xmlNodeSetPtr xmlXPathNodeTrailing (:xmlNodeSetPtr,:xmlNodePtr) shlib
@c xmlNodeSetPtr xmlXPathTrailing (:xmlNodeSetPtr,:xmlNodeSetPtr) shlib
@c Int32 xmlXPathRegisterNs (:xmlXPathContextPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c Ptr{:xmlChar} xmlXPathNsLookup (:xmlXPathContextPtr,Ptr{:xmlChar}) shlib
@c None xmlXPathRegisteredNsCleanup (:xmlXPathContextPtr,) shlib
@c Int32 xmlXPathRegisterFunc (:xmlXPathContextPtr,Ptr{:xmlChar},:xmlXPathFunction) shlib
@c Int32 xmlXPathRegisterFuncNS (:xmlXPathContextPtr,Ptr{:xmlChar},Ptr{:xmlChar},:xmlXPathFunction) shlib
@c Int32 xmlXPathRegisterVariable (:xmlXPathContextPtr,Ptr{:xmlChar},:xmlXPathObjectPtr) shlib
@c Int32 xmlXPathRegisterVariableNS (:xmlXPathContextPtr,Ptr{:xmlChar},Ptr{:xmlChar},:xmlXPathObjectPtr) shlib
@c xmlXPathFunction xmlXPathFunctionLookup (:xmlXPathContextPtr,Ptr{:xmlChar}) shlib
@c xmlXPathFunction xmlXPathFunctionLookupNS (:xmlXPathContextPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c None xmlXPathRegisteredFuncsCleanup (:xmlXPathContextPtr,) shlib
@c xmlXPathObjectPtr xmlXPathVariableLookup (:xmlXPathContextPtr,Ptr{:xmlChar}) shlib
@c xmlXPathObjectPtr xmlXPathVariableLookupNS (:xmlXPathContextPtr,Ptr{:xmlChar},Ptr{:xmlChar}) shlib
@c None xmlXPathRegisteredVariablesCleanup (:xmlXPathContextPtr,) shlib
@c xmlXPathParserContextPtr xmlXPathNewParserContext (Ptr{:xmlChar},:xmlXPathContextPtr) shlib
@c None xmlXPathFreeParserContext (:xmlXPathParserContextPtr,) shlib
@c xmlXPathObjectPtr valuePop (:xmlXPathParserContextPtr,) shlib
@c Int32 valuePush (:xmlXPathParserContextPtr,:xmlXPathObjectPtr) shlib
@c xmlXPathObjectPtr xmlXPathNewString (Ptr{:xmlChar},) shlib
@c xmlXPathObjectPtr xmlXPathNewCString (Ptr{:Uint8},) shlib
@c xmlXPathObjectPtr xmlXPathWrapString (Ptr{:xmlChar},) shlib
@c xmlXPathObjectPtr xmlXPathWrapCString (Ptr{:Uint8},) shlib
@c xmlXPathObjectPtr xmlXPathNewFloat (:Float64,) shlib
@c xmlXPathObjectPtr xmlXPathNewBoolean (:Int32,) shlib
@c xmlXPathObjectPtr xmlXPathNewNodeSet (:xmlNodePtr,) shlib
@c xmlXPathObjectPtr xmlXPathNewValueTree (:xmlNodePtr,) shlib
@c None xmlXPathNodeSetAdd (:xmlNodeSetPtr,:xmlNodePtr) shlib
@c None xmlXPathNodeSetAddUnique (:xmlNodeSetPtr,:xmlNodePtr) shlib
@c None xmlXPathNodeSetAddNs (:xmlNodeSetPtr,:xmlNodePtr,:xmlNsPtr) shlib
@c None xmlXPathNodeSetSort (:xmlNodeSetPtr,) shlib
@c None xmlXPathRoot (:xmlXPathParserContextPtr,) shlib
@c None xmlXPathEvalExpr (:xmlXPathParserContextPtr,) shlib
@c Ptr{:xmlChar} xmlXPathParseName (:xmlXPathParserContextPtr,) shlib
@c Ptr{:xmlChar} xmlXPathParseNCName (:xmlXPathParserContextPtr,) shlib
@c Float64 xmlXPathStringEvalNumber (Ptr{:xmlChar},) shlib
@c Int32 xmlXPathEvaluatePredicateResult (:xmlXPathParserContextPtr,:xmlXPathObjectPtr) shlib
@c None xmlXPathRegisterAllFunctions (:xmlXPathContextPtr,) shlib
@c xmlNodeSetPtr xmlXPathNodeSetMerge (:xmlNodeSetPtr,:xmlNodeSetPtr) shlib
@c None xmlXPathNodeSetDel (:xmlNodeSetPtr,:xmlNodePtr) shlib
@c None xmlXPathNodeSetRemove (:xmlNodeSetPtr,:Int32) shlib
@c xmlXPathObjectPtr xmlXPathNewNodeSetList (:xmlNodeSetPtr,) shlib
@c xmlXPathObjectPtr xmlXPathWrapNodeSet (:xmlNodeSetPtr,) shlib
@c xmlXPathObjectPtr xmlXPathWrapExternal (Ptr{:None},) shlib
@c Int32 xmlXPathEqualValues (:xmlXPathParserContextPtr,) shlib
@c Int32 xmlXPathNotEqualValues (:xmlXPathParserContextPtr,) shlib
@c Int32 xmlXPathCompareValues (:xmlXPathParserContextPtr,:Int32,:Int32) shlib
@c None xmlXPathValueFlipSign (:xmlXPathParserContextPtr,) shlib
@c None xmlXPathAddValues (:xmlXPathParserContextPtr,) shlib
@c None xmlXPathSubValues (:xmlXPathParserContextPtr,) shlib
@c None xmlXPathMultValues (:xmlXPathParserContextPtr,) shlib
@c None xmlXPathDivValues (:xmlXPathParserContextPtr,) shlib
@c None xmlXPathModValues (:xmlXPathParserContextPtr,) shlib
@c Int32 xmlXPathIsNodeType (Ptr{:xmlChar},) shlib
@c xmlNodePtr xmlXPathNextSelf (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextChild (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextDescendant (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextDescendantOrSelf (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextParent (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextAncestorOrSelf (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextFollowingSibling (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextFollowing (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextNamespace (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextAttribute (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextPreceding (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextAncestor (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c xmlNodePtr xmlXPathNextPrecedingSibling (:xmlXPathParserContextPtr,:xmlNodePtr) shlib
@c None xmlXPathLastFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathPositionFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathCountFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathIdFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathLocalNameFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathNamespaceURIFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathStringFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathStringLengthFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathConcatFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathContainsFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathStartsWithFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathSubstringFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathSubstringBeforeFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathSubstringAfterFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathNormalizeFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathTranslateFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathNotFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathTrueFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathFalseFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathLangFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathNumberFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathSumFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathFloorFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathCeilingFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathRoundFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathBooleanFunction (:xmlXPathParserContextPtr,:Int32) shlib
@c None xmlXPathNodeSetFreeNs (:xmlNsPtr,) shlib

